### ISSUE TITLE
Control remote companion

### ISSUE THREAD

**Issue by fmalcher** [bitfocus/io.bitfocus.companion-plugin#2]
I'm super happy to see the plugin communicate via WebSocket. Even better, it already considers controlling a remote companion instance. This works fine by just changing the IP in the plugin source code.

https://github.com/bitfocus/io.bitfocus.companion-plugin/blob/master/app.js#L55

Your comment says:
> In the future, let people select external companion

Will you share your thoughts on how this could be implemented?
Should the companion IP be set in a config file or through the Elgato UI? If the latter, what ways are there to set global settings for the plugin?

Thanks!

**Comment by rehofman** [comment]
I would like to have the same functionality. I would like to have two profiles which each controls a different instance of companion. Can we just expose the IP in the settings of the button? I think that would be easy to implement, and by default we can leave it on localhost.
![streamdeck_with_IP](https://user-images.githubusercontent.com/14074772/153711897-6656bbf5-6896-4b3f-b9b7-8c0100326a95.png)

**Comment by Julusian** [comment]
I believe the problem is that there isnt any suitable place to input a 'global' ip address. It could be done per button, but that will not be at all friendly to configure, and will require some work to ensure that this code can handle there being connected to multiple companion instances concurrently.

Instead, you should consider using [Companion Satellite](https://github.com/bitfocus/companion-satellite), which is designed to connect a local streamdeck to a remote companion installation

**Comment by avremy** [comment]
+1

**Comment by abdullahseba** [comment]
> I believe the problem is that there isnt any suitable place to input a 'global' ip address. It could be done per button, but that will not be at all friendly to configure, and will require some work to ensure that this code can handle there being connected to multiple companion instances concurrently.
> 
> Instead, you should consider using [Companion Satellite](https://github.com/bitfocus/companion-satellite), which is designed to connect a local streamdeck to a remote companion installation

The satellite doesn't work with the plugin.  I've been trying to get it to work, but there no settings anywhere for this.  You have to install the server on the same device that has the deck plugged into it for it to work.

**Comment by fmalcher** [comment]
> The satellite doesn't work with the plugin. I've been trying to get it to work, but there no settings anywhere for this. You have to install the server on the same device that has the deck plugged into it for it to work.

The hacky solution is to set the IP address manually in the [StreamDeck plugin code](https://github.com/bitfocus/io.bitfocus.companion-plugin/blob/master/app.js#L80). I've been using this for years, but you have to change it again after every update of the plugin.

**Comment by abdullahseba** [comment]
Any update on this?  I tried updating the IP address in what is now plugin.js but although the connection error disappeared, the companion dashboard did not show any connections.

**Comment by abdullahseba** [comment]
> Instead, you should consider using [Companion Satellite](https://github.com/bitfocus/companion-satellite), which is designed to connect a local streamdeck to a remote companion installation

The problem is that the Companion Satelite doesn't support the plugin!  At least, I can't see anything in settings, but it would be wonderful if I was wrong.

**Comment by davojc** [comment]
I would love to see this too. It should be fairly straightforward as Elgato support global settings: [https://docs.elgato.com/streamdeck/sdk/guides/settings](https://docs.elgato.com/streamdeck/sdk/guides/settings)

Might be tricky if you want to connect to multiple but even that might be simply storing against profile.

**Comment by Julusian** [comment]
Honestly, I think this is also a little blocked on companion supporting this well too.
While in theory it is possible to do today, I think that companion will get very confused if there is more than one connection from the plugin.  
And the UX in companion is confusing, because enabling support for the plugin disables companion connecting to streamdecks directly.

**Comment by josephdadams** [comment]
PR #13 allows the plugin to identify a companion IP other than localhost.
