### ISSUE TITLE
Stream Deck does not install the companion plugin[BUG]

### ISSUE THREAD

**Issue by Orion1318** [bitfocus/io.bitfocus.companion-plugin#6]
### Is this a bug in companion itself or a module?

- [X] I believe this to be a bug in companion

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

![Screenshot 2023-06-09 113818](https://github.com/bitfocus/companion/assets/136074589/58e9d04b-c648-4b70-9607-fc74a0eaddac)
sorry if I don't complete all the fields or if I'm in the wrong section, I'm a newbie about it.
I want to clarify that I installed the plugin some time ago, it was last used last Saturday, today I wanted to fix some things on my application (resolum Arena) but it wasn't recognized by the Stream Deck, I'm going to look for the reason, it was not installed, so I go back to the store to install the plugin again, it gives me confirmation, but it is not among the available plugins. I close and open the store again and it asks me to install it again.
attempts to update the Stream Deck, I try to install several plugins successfully, only Companion is not installed.
the companion app doesn't recognize my Stream Deck because it doesn't actually have the plugin installed.
it is a deadlock, only because the plugin is not installed correctly. I also reported the same problem to Elgato.
from the image you can see how it is installed but not present in the library, and in the buttons it was previously present.

### Steps To Reproduce

1. Open the Stream Deck application.
2. Note if the companion button plugin is present in the library, if it is not present proceed to step 3.
3. go to the store and try to install it again.
4. go back to the library and see if it is present in the library again, if it is not present it is in a deadlock situation.

### Expected Behavior

I expected to find the plugin in my library.
after proceeding with the installation again I expected to find it again in the library.

### Environment (please complete the following information)

```markdown
- OS: windows  11
- Browser: google chorme Version 114.0.5735.110
- Companion Version: v3.0.0-rc1+5909-v3-0.0-rc1-725c3583
- Stream Deck version:6.2.1.18825
```

**Comment by Julusian** [comment]
Have you tried reinstalling the elgato streamdeck software?
or perhaps manually deleting the plugin from your machine and reinstalling (its somewhere under %APPDATA%)? I think I remember seeing some log files nearby too, perhaps one includes an error?

I don't know what we will be able to do about this, I have checked on a couple of windows machines and it will install fine for me, so Im not sure how much more I can help as it sounds like the elgato software doing something wrong

**Comment by Orion1318** [comment]
Hi Julian,
I followed the procedure to reinstall the Elgato software and apparently by
doing so it started working again, now the plugin installs it safely and
keeps it even on system restarts.
I hope my report solves these little bugs that happen when you update the
software.
thanks and good job,
Federico Saracino

Il giorno mer 14 giu 2023 alle ore 21:12 Julian Waller <
***@***.***> ha scritto:
