### ISSUE TITLE
Stream Deck Plus Knob Press/Release not working

### ISSUE THREAD

**Issue by techdude-777** [bitfocus/io.bitfocus.companion-plugin#9]
When using the dial knobs I can not utilise the Press / Release action.
Left/Right is workinng but not the press/release action.

**Comment by Julusian** [comment]
Elgato broke this intentionally in the 6.5 update. This is documented in their developer changelogs, but as this plugin is only minimally maintained/looked after, we didn't notice https://docs.elgato.com/sdk/plugins/changelog
Also the fact that this was first reported in may, 5 months after the release of 6.5 indicates how little this plugin is used.

I have a fix (https://github.com/bitfocus/io.bitfocus.companion-plugin/commit/64835c405c713b06c7e427840f084cda7802f7d6), am not sure if it is worth releasing before the overhaul that I am almost finished on

**Comment by Sindbad5** [comment]
Should it be fixed in V3.3.0 - because it doesn't work for me.

**Comment by haakonnessjoen** [comment]
Have you tried it with the 3.0 version of the plugin released yesterday in the elgato plugin market?

**Comment by Sindbad5** [comment]
Hey Håkon,
Thank you for your quick reply and the hint.

My Stream Deck plugins will be updated automatically (if possible).
I had obviously tested it shortly before the update.

The click with the rotation knob works. The touch bar seems only to be for the visualization/representation (no click/touch function).
